online/semana_2/ecommerce/config/routes.rb
Rails.application.routes.draw do
  root :to => "laptops#index"

resources :laptops

end

online/semana_2/ecommerce/app/models/laptop.rb
class Laptop < ActiveRecord::Base
end

online/semana_2/ecommerce/app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
	def index
		@laptops = Laptop.all
	end
	
	def show
		@laptop = Laptops.find(params[:id])
	end

	def new
   		@laptop = Laptop.new
  	end

  	def edit
  		@laptop =Laptop.find(params[:id ])
  	end


  	def create
     	@laptop = Laptop.new(laptop_params)
     	@laptop.save
     	redirect_to laptop_path(@laptop)
  	end

  	def update
  		@laptop = Laptop.find(params[:id])
  		@laptop.update(laptop_params)
  		redirect_to laptop_path(@laptop)
  	end

  	private
    	 def laptop_params
          	params.require(:laptop).permit(:brand, :model)
    end

end

online/semana_2/ecommerce/app/helpers/laptops_helper.rb
module LaptopsHelper
end

online/semana_2/ecommerce/app/views/laptops/edit.html.erb
<h1>Editing laptop</h1>

<%= form_for :laptop, url: laptop_path(@laptop), method: :patch do |f| %>
  <p>
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </p>

  <p>
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </p>

  <p>
    <%= f.label :processorBrand %><br>
    <%= f.text_field :processorBrand %>
  </p>

  <p>
   <%= f.label :ramSize %><br>
   <%= f.text_field :ramSize %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<p>
  <%= link_to 'Back', laptops_path %>
</p>

online/semana_2/ecommerce/app/views/laptops/index.html.erb
<h1> Listing laptops <h1>
<% @laptops.each do |laptop|%>
	<div><%= laptop.brand %></div>
		<% link_to 'Show', laptop.path(laptop) %>
		<% link_to 'Edit', edit_laptop.path(laptop) %>

<% end %>

<p>
    <%= link_to 'New laptop', new_laptop_path %>
</p>

online/semana_2/ecommerce/app/views/laptops/new.html.erb
<%= form_for @laptop do |f| %>
  <p>
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </p>

  <p>
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </p>

  <p>
    <%= f.label :processorBrand %><br>
    <%= f.text_field :processorBrand %>
  </p>

  <p>
   <%= f.label :ramSize %><br>
   <%= f.text_field :ramSize %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<p>
  <%= link_to 'Back', laptops_path %>
</p>

online/semana_2/ecommerce/app/views/laptops/show.html.erb
<h3>
  <strong>Laptop:</strong>
  <%= @laptop.brand %>

</h3>

<p>
  <strong>Processor, RAM:</strong>
  <%= @laptop.processorBrand %>

</p>

<p>
    <%= link_to 'Edit', edit_article_path(@article)%> |
	<%= link_to 'Back', laptops_path %>
</p>