facetoface/semana_2/timetracking/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'site#home'
  resources :projects do
  	resources :entries
  end
end

facetoface/semana_2/timetracking/app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :project
	validates :hours, numericality: true
	validates :minutes, numericality: true
	validates :date, presence: true
	validates :hours, presence: true
	validates :minutes, presence: true
	validates :project_id, presence: true
end

facetoface/semana_2/timetracking/app/models/project.rb
class Project < ActiveRecord::Base
	has_many :entries
	validates :name, presence: true
	validates :name, uniqueness: true
	validates :name, length: {maximum: 30}
	validates :name, format: {with: /\A[a-zA-Z0-9\s]+\z/}

	def self.iron_find param
		where(id: param).first
	end

	def self.clean_old
		one_week_ago = Date.current - 7
		p_to_destroy = Project.where("created_at < ?", one_week_ago)
		p_to_destroy.destroy_all
	end

	def self.last_created_projects param
		order(created_at: :desc).limit(param)
	end
	def calculate_worked_hours month, year
		all_entries = self.entries
		all_selected_entries = all_entries.select do |entry|
			entry.date.month == month && entry.date.year == year
		end
		all_selected_entries.reduce(0){|sum, entry| sum + entry.hours}
	end
end

facetoface/semana_2/timetracking/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def index
		@project = Project.find params[:project_id]
		@entries = @project.entries
	end
	def new
		@project = Project.find params[:project_id]
		@entry = @project.entries.new
	end
	def create
		@project = Project.find params[:project_id]
		@entry = @project.entries.new entry_params
		if @entry.save
			flash[:notice] = "Entry created successfully"
			redirect_to project_entries_path(@project)
		else
			flash[:alert] = "Entry hasn't been created successfully"
			render 'new'
		end
	end

	def edit
		@project = Project.find params[:project_id]
		@entry = @project.entries.find params[:id]
	end
	def update
		@entry = Entry.find(params[:id])

		if @entry.update_attributes entry_params
			flash[:notice] = "Entry updated successfully"
			redirect_to action: 'index'
		else
			flash.now[:errors] = @entry.errors.full_messages
			render 'edit'
		end
	end

	def destroy
		@project = Project.find params[:project_id]
		@entry = @project.entries.find params[:id]
		@entry.destroy
		redirect_to projects_path
	end

	private
	def entry_params
		params.require(:entry).permit(:hours, :minutes, :comments, :date)
	end
end

facetoface/semana_2/timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.last_created_projects(10)
	end

	def show
		begin
			@project = Project.find params[:id]
		rescue ActiveRecord::RecordNotFound
			render 'no_projects_found', layout: 'admin'
		end
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new project_params
		if @project.save
			redirect_to @project
		else
			render 'new'
		end
	end

	def edit
		@project = Project.find params[:id]
	end

	def update
		@project = Project.find params[:id]
		if @project.update project_params
			redirect_to @project
		else
			render 'edit'
		end
	end

	def destroy
		project = Project.find params[:id]
		project.destroy
		redirect_to projects_path
	end

	private
	def project_params
		params.require(:project).permit(:name, :description)
	end
end

facetoface/semana_2/timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
	end
	def contact
	end
end

facetoface/semana_2/timetracking/app/helpers/application_helper.rb
module ApplicationHelper
	def flash_message
		display_message(:alert) || display_message(:notice)
	end

	private
	
	def display_message (type)
		if flash[type]
			content_tag :div, class: type do
				content_tag :p do
					flash[type]
				end
			end
		end
	end
end

facetoface/semana_2/timetracking/app/helpers/entries_helper.rb
module EntriesHelper
end

facetoface/semana_2/timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

facetoface/semana_2/timetracking/app/views/entries/edit.html.erb
<%= form_for [@project, @entry] do |f|%>
	<%= f.label :hours %>
	<%= f.text_field :hours %>
	<br>
	<%= f.label :minutes %>
	<%= f.text_field :minutes %>
	<br>
	<%= f.label :comments %>
	<%= f.text_area :comments %>
	<br>
	<%= f.label :date %>
	<%= f.date_field :date %>
	<br>

	<%= f.submit 'Save' %>
	<%= link_to('Back to project', project_path(@project)) %>
<% end %>

facetoface/semana_2/timetracking/app/views/entries/index.html.erb
<% flash_message %>

<ul>
	<% @entries.each do |entry| %>
	<li>
		<%= entry.id %> - 
		<%= entry. hours %> h - 
		<%= entry.minutes %> m - 
		<%= entry.date %>
		<%= link_to('Edit entry', edit_project_entry_path(@project, entry)) %>
		<%= link_to('Delete entry', project_entry_path(@project, entry), method: :delete, data: {confirm: 'Are you sure?'}) %>
	</li>
	<% end %>
	<li><%= link_to('Back', projects_path) %></li>
</ul>

facetoface/semana_2/timetracking/app/views/entries/new.html.erb
<% flash_message %>

<% if @entry.errors.any? %>
	<ul>
		<% @entry.errors.full_messages.each do |error_msg| %>
		<li><%= error_msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for [@project, @entry] do |f|%>
	<%= f.label :hours %>
	<%= f.text_field :hours %>
	<br>
	<%= f.label :minutes %>
	<%= f.text_field :minutes %>
	<br>
	<%= f.label :comments %>
	<%= f.text_area :comments %>
	<br>
	<%= f.label :date %>
	<%= f.date_field :date %>
	<br>

	<%= f.submit 'Save' %>
	<%= link_to('Back to project', project_path(@project)) %>
<% end %>